const content = {
  en: {
    1: '<p>You fell into the abyss. You don’t understand how it happened—this wasn’t supposed to happen. This place shouldn’t even exist; it’s just a theoretical experiment. You never thought it would happen to you, but here you are, experiencing the abyss firsthand. You wonder if others have fallen in too. You’ve never heard any accounts of it, and that fact tightens your throat.</p>',
    2: '<p>Wait a moment. You realize you can’t feel your throat. In fact, you can’t feel anything.</p><p>You try, with all your mental effort, to become aware of your senses, but they’re blocked—nothing enters your nervous system.</p><p>You mentally perceive your surroundings: there is nothing. In fact, there is no “surroundings.” Only your consciousness and your solitude.</p>',
    3: '<p>"I shouldn’t have pressed that button," you tell yourself, recalling how you got here. It was your fault, that’s true, and you regret it because you’re not sure you’ll be able to get out. And yet, deep down, something intrigues you. You begin to ask yourself questions.</p><p>How is it possible that in a place where apparently nothing exists, your mind does? Does your body exist? Does this mean that consciousness precedes the body?</p><p>You feel thrilled thinking about the scientific and philosophical breakthroughs you’ll present. You imagine telling every world about your discoveries. For the first time, you envision success in your life.</p><p>But then you realize—you don’t know how to get out.</p>',
    4: '<p>Panic takes hold of the only thing you have: your mind. In the worst-case scenario, you’ll never get out and become a completely isolated consciousness for eternity. That should be considered a form of torture in the 30th century.</p><p>You need to relax to think clearly. You recall a technique taught to you in the quantum astronaut training program. You search your memory—it’s in there somewhere.</p><p>Ah, yes. Imagine a circle expanding and contracting and breathe with its rhythm. When it expands, inhale. When it contracts, exhale.</p><p>Suddenly, something happens that the program didn’t prepare you for. The circle is right in front of you. Not metaphorically. Literally in front of you.</p>',
    5: '<p>When it expands, inhale. When it contracts, exhale.</p>',
    6: '<p>Falling, unexpectedly, into a distorted region of the universe isn’t easy. There are no dimensions—only void. No time, no space. Just consciousness. There’s not much you can do to escape; everything you were taught about these places was purely theoretical, and no one ever came back to talk about it.</p><p>You feel deep sadness and nostalgia. Also confusion—you don’t understand how that circle appeared there. You don’t even understand where “there” is.</p><p>You remain trapped in the loop. You realize that, in truth, the only thing disturbing you is your own consciousness. There is nothing beyond that. You return your attention to the circle. It remains in front of you, unmoving, just like you.</p>',
    7: '<p>You give up. You don’t know what else to do. You see no way out. You feel your existence, but at the same time, it seems like a dream. You only wish to return to what you were doing before pressing that stupid button—you were on your ship, on an exploratory mission, heading toward a distant star.</p><p>You remember, you visualize what you were witnessing right before falling into the abyss: a shooting star moving in different directions. It was a tiny white dot far away, but poetic enough to bring a tear to your eye. You remember that moment fondly.</p><p>The memory draws you in…</p>',
    8: '<p>If the abyss is inhabited only by consciousness, then everything that’s happening—from the sensory deprivation to the images—is a product of your mind.</p><p>Your imagination ignites. Motivation embraces you. You begin to create shapes, stars, glowing all around you. You turn this dark place into an oasis, your own little paradise.</p><p>You surround yourself with beautiful, glowing, dreamlike figures that glide around you and remind you of the joy of simplicity.</p><p>You contemplate your tiny cosmos and, once again, let yourself be drawn in…</p>',
    9: '<p>You could create a new ship, a perfect world—even a universe. It could be perfect, free from violence and pain. You could recreate everything, right here, in your own universe.</p><p>But something feels wrong. Even though nothing guarantees the universe you come from isn’t also the product of another consciousness’s abyss, you feel uneasy at the thought of abandoning it and staying here, playing God.</p><p>Everything goes dark again, and you simply surrender to the full experience of the night. You let yourself go. And with you go your ideas, your thoughts, your identity. You become part of the abyss.</p><p>Or the abyss becomes you.</p>',
    10: '<p>You don’t know how much time has passed. But you are aware that you were and are part of that totality. Of that game of creation and disintegration, of existence and non-existence. Both live within you, and you live within both. That is the abyss. It is duality.</p><p>You finally understand—there is a way out. You just have to create it.</p>',
  },
  es: {
    1: '<p>Caíste en el abismo. No entendés cómo ocurrió, esto no debía suceder. Este sitio no debería existir, es solo un experimento teórico. Nunca pensaste que te iba a tocar, pero acá estás, experimentando de primera mano el abismo. Te preguntás si otras personas habrán caído también. No conocés testimonios al respecto y ese hecho hace que se te cierre la garganta.</p>',
    2: '<p>Un momento. Te percatás que no sentís tu garganta. De hecho, no sentís nada.</p><p>Intentás, con todo esfuerzo psíquico, hacerte consciente de tus sentidos pero están bloqueados, nada ingresa a tu sistema nervioso.</p><p>Percibís mentalmente tu alrededor: no hay nada. De hecho, no hay alrededor. Solo tu conciencia y tu soledad.</p>',
    3: '<p>“No debí presionar ese botón”, te castigás mientras recordás cómo llegaste. Fue tu culpa, es verdad, y te arrepentís porque no tenés certeza de que vas a lograr salir. Aunque, en el fondo, hay algo que te intriga. Comenzás a hacerte preguntas. </p><p>¿Cómo es posible que en un sitio donde aparentemente no hay nada, exista tu mente? ¿Existe tu cuerpo? ¿Esto quiere decir que la conciencia antecede al cuerpo?</p><p>Te emociona pensar en los avances a la ciencia y la conciencia que vas a presentar. Te imaginás contándole a todos los mundos sobre tus descubrimientos. Ves, por primera vez, el éxito en tu vida.</p><p>Pero te das cuenta. No sabés cómo salir. </p>',
    4: '<p>El pánico se apodera de lo único que tenés: tu mente. En el peor de los casos nunca vas a salir y vas a ser una conciencia aislada completamente en la eternidad. Eso debería ser catalogado como una forma de tortura del siglo XXX. </p><p>Necesitás relajarte para pensar con claridad. Recordás una técnica que te enseñaron en el programa de preparación para astronautas cuánticos. Haces memoria, en algún lado está.</p><p>Ah, sí. Imaginar un círculo que se agranda y se achica y respirar a su ritmo. Cuando se agranda, inhalás. Cuando se achica, exhalas. </p><p>De pronto, sucede algo para lo que no te habían preparado en el programa. El círculo está frente tuyo. No de forma metafórica. Está, literalmente, frente tuyo. </p>',
    5: '<p>Cuando se agranda, inhalás. Cuando se achica, exhalás.</p>',
    6: '<p>Caer, desprevenidamente, en una región del universo distorsionada no es fácil. No hay dimensiones, solo vacío. No hay tiempo, no hay espacio. Solo conciencia. No hay mucho que puedas hacer para escapar, todo lo que te enseñaron sobre estos lugares era puramente teórico y nunca nadie salió para contarlo. </p><p>Te entra una gran tristeza y nostalgia. Confusión también, no entendés cómo es que ese círculo apareció ahí. Ni siquiera entendés dónde es <i>ahí</i>. </p><p>Seguís en el bucle. Te das cuenta que, en verdad, lo único que te perturba es tu propia conciencia. No hay nada más allá de eso. Volvés a prestarle atención al círculo. Sigue delante tuyo pero no se mueve, está inmóvil, como vos.</p>',
    7: '<p>Te rendís. No sabés qué más hacer. No ves una salida. Sentís tu existencia, pero a la vez te parece un sueño. Solo deseás volver a lo que estabas haciendo antes de presionar ese estúpido botón: ibas en tu nave, en una misión exploratoria, rumbo a una estrella lejana. </p><p>Recordás, visualizás, lo que estabas presenciando justo antes de caer en el abismo. Una estrella fugaz que se movía en distintas direcciones. Era un pequeñísimo punto blanco muy lejano, pero lo suficientemente poético como para hacerte derramar una lágrima. Recordás ese instante con mucho cariño. </p><p>Te absorbe el recuerdo…</p>',
    8: '<p>Si en el abismo solo habita conciencia, significa que todo lo que está sucediendo, desde la privación sensorial hasta las imágenes, son producto de tu mente. </p><p>Tu imaginación se enciende. La motivación te abraza. Empezás a crear formas, estrellas, brillando a tu alrededor. Convertís ese lugar oscuro en un oasis, tu pequeño paraíso. </p><p>Te rodeas de hermosas figuras brillantes e idílicas que se deslizan a tu alrededor y te recuerdan la belleza de contentarse con lo simple. </p><p>Contemplás tu pequeño cosmos y, una vez más, te dejas absorber… </p>',
    9: '<p>Podrías crear una nueva nave, un mundo perfecto, un universo incluso. Podría ser perfecto, libre de violencia y dolor. Podrías crear todo de nuevo, allí, en tu propio universo. </p><p>Aunque algo no está bien. Si bien nada te asegura que el universo del que venís no es producto de otro abismo de otra conciencia, te sentís mal por tener la idea de abandonarlo y quedarte jugando a ser Dios. </p><p>Todo vuelve a estar oscuro y, simplemente, te sumís en la experiencia completa de la noche. Te dejas ir. Y con vos se van tus ideas, tus pensamientos, tu identidad. Te convertís en parte del abismo.</p><p>O el abismo se convierte en vos.</p>',
    10: '<p>No sabés cuánto tiempo transcurrió. Pero sos consciente de que fuiste y sos parte de esa totalidad. De ese juego de creación y desintegración, de existencia e inexistencia. Ambas viven en vos y vos vivís en ambas. Eso es el abismo. Es la dualidad.</p><p>Por fin lo entendés, hay una salida. Solo tenés que crearla.</p>',
  }
};
export default content;
